apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: bookingsvc
     labels:
       app: bookingsvc
   spec:
     containers:
       - name: bookscvcluster
         image: "" 
         imagePullPolicy: Always
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: NODE_ENV
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: env-database
                key: DATABASE
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: env-database
                key: PORT
          - name: HOSTNAME
            valueFrom:
              secretKeyRef:
                name: env-database
                key: HOSTNAME
          - name: PROTOCOL
            valueFrom:
              secretKeyRef:
                name: env-database
                key: PROTOCOL
         ports:
         - containerPort: 3000
         livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: bookingsvc
 labels:
   app: bookingsvc
spec:
 type: NodePort
 selector:
   app: bookingsvc
 ports:
  - protocol: TCP
    name: bookingsvc
    port: 3000
    targetPort: 3000  