apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.metadata.name }} 
  labels:
    app: {{ .Values.serviceMonitor.metadata.labels.team }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.serviceMonitor.specs.selector.matchLabels.app }} 
  endpoints:
  - port: {{ .Values.serviceMonitor.specs.port}}