apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: saqrairwayingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
   - http:
      paths:
      - path: /listingsvc
        backend:
          serviceName: listingsvc
          servicePort: 7000